### ISSUE TITLE
Half-a-lines

### ISSUE THREAD

**Issue by alicebob** [ActiveState/tail#35]
I've got a file which is growing fast (a kernel packet log). This is line based, and lines are usually around 900 bytes long.

Sometimes range t.Lines gives a partial line (not ending in "\n"), even though I have not set MaxLineSize. This line is then 512 bytes long.

It seems this is caused by this if:
https://github.com/ActiveState/tail/blob/master/tail.go#L217
although I would expect the next 'if' to be the one we want in this case (wait for more data to complete the line).

Linux 3.13.7, go 1.3 and this is used to open the file:
``` go
      t, err := tail.TailFile(file, tail.Config{
          Follow: true,
          ReOpen: true,
          Location: &tail.SeekInfo{
              Offset: 0,
              Whence: os.SEEK_END,
          },
      })
```

**Comment by troy** [comment]
I just backed this with $110 on Bountysource [here](https://www.bountysource.com/issues/3007897-half-a-lines). From what I can see, @2sidedfigure's PR #40 solves this except test coverage.

Any fix that prevents partial lines (as described in @rbroemeling's comments) and satisfies the maintainer's requirements for merging qualifies for the bounty.
