### ISSUE TITLE
Please use stable version of fsnotify

### ISSUE THREAD

**Issue by awillis** [ActiveState/tail#46]
Currently you import "github.com/howeyc/fsnotify". Could you please switch to import "gopkg.in/fsnotify.v0" instead? It should be a drop-in replacement. This helps when I have other code that needs to use fsnotify.

**Comment by KacperPerschke** [comment]
Better to `import "gopkg.in/fsnotify/fsnotify.v1"` or `import "github.com/fsnotify/fsnotify"`
