### ISSUE TITLE
Single inotify instance with multiple watchers

### ISSUE THREAD

**Issue by wagerlabs** [ActiveState/tail#51]
An fd-per-watch quickly consumes more file descriptors than are allowed. Would you accept a patch that uses a single inotify instance and multiple watchers? This appears to be the [approach recommended by the Linux kernel docs][1].

There's a [stumbling block][2] that would require modifying the API. The new approach would eliminate the global inotify tracker variable and create new file watchers using a supplied instance of a tracker. 

Please let me know what you think!

P.S. This is for Papertrail's remote_syslog2, to resolve [this issue][3].

[1]: https://github.com/torvalds/linux/blob/164c09978cebebd8b5fc198e9243777dbaecdfa0/Documentation/filesystems/inotify.txt#L221-L223
[2]: https://github.com/ActiveState/tail/blob/22e519566e0262c14f3b181ec0e192be38abb05b/watch/inotify.go#L14
[3]: https://github.com/papertrail/remote_syslog2/issues/4

**Comment by jandubois** [comment]
> There's a stumbling block that would require modifying the API. The new approach would eliminate the global inotify tracker variable and create new file watchers using a supplied instance of a tracker.

I think it would be preferable to keep the old API available for backwards compatibility and offer the new API as an alternative. Is there anything preventing this?

Given that most go dependency managers don't implement semantic versioning, changing the API would otherwise require changing the package name.

**Comment by wagerlabs** [comment]
I don't think I can provide both APIs in the same package. We could use [gopkg.in][1], though, and map the new API to a new branch. Would that work?

The reason I cannot keep the old API is that [initializing the file watcher][2] may return an error. The error would need to be handled so initialization cannot be done [once per package][3] like now.

[1]: http://labix.org/gopkg.in
[2]: https://github.com/wagerlabs/tail/blob/master/watch/inotify.go#L28
[3]: https://github.com/wagerlabs/tail/blob/master/watch/inotify.go#L135

**Comment by wagerlabs** [comment]
I suggest using `https://gopkg.in/ActiveState/tail.v0` for the old API and `https://gopkg.in/ActiveState/tail.v1` for the new one. The latter would map to the `v1` branch.

**Comment by srid** [comment]
+1. And, I support the use of gopkg.in for using specific API revision (note to ActiveState folks – internal Stackato packages can simply point to the `gopkg.in/...v0` endpoint). 

Once this is fully implemented, we may also get rid of the [Cleanup function](https://github.com/ActiveState/tail/pull/20).

**Comment by wagerlabs** [comment]
Here's an [implementation](https://github.com/ActiveState/tail/pull/53).
